### ISSUE TITLE
在华为荣耀10，os9.0上摇晃手机点击dev setting就崩溃

### ISSUE THREAD

**Issue by s3hengwu** [ctripcorp/CRN#7]
在华为荣耀10，os9.0上摇晃手机点击dev setting就崩溃

**Comment by s3hengwu** [comment]
顺便反馈一下，在雷电模拟器上点应用图标就崩溃
 Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
        at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:548)
        at android.app.Activity.onApplyThemeResource(Activity.java:3686)
        at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
        at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
        at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by chufengma** [comment]
Fix at [72404b9](https://github.com/ctripcorp/CRN/commit/72404b9d37f2bc6633971a6c97849478af7fe121)

感谢反馈
